#ifndef __PRIVATE_H__
#define __PRIVATE_H__


//extern int send_udp();

char *keycode[] = {
  "Reserved",
  "Esc",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "0",
  "Minus",
  "Equal",
  "Backspace",
  "Tab",
  "Q",
  "W",
  "E",
  "R",
  "T",
  "Y",
  "U",
  "I",
  "O",
  "P",
  "Left Brace",
  "Right Brace",
  "Enter",
  "Left Control",
  "A",
  "S",
  "D",
  "F",
  "G",
  "H",
  "J",
  "K",
  "L",
  "Semicolon",
  "Apostrophe",
  "Grave",
  "Left Shift",
  "Backslash",
  "Z",
  "X",
  "C",
  "V",
  "B",
  "N",
  "M",
  "Comma",
  "Dot",
  "Slash",
  "Right Shift",
  "Keypad Asterisk",
  "Left Alt",
  "Space",
  "Caps Lock",
  "F1",
  "F2",
  "F3",
  "F4",
  "F5",
  "F6",
  "F7",
  "F8",
  "F9",
  "F10",
  "Num Lock",
  "Scroll Lock",
  "Keypad 7",
  "Keypad 8",
  "Keypad 9",
  "Keypad Minus",
  "Keypad 4",
  "Keypad 5",
  "Keypad 6",
  "Keypad Plus",
  "Keypad 1",
  "Keypad 2",
  "Keypad 3",
  "Keypad 0",
  "Keypad Dot",
  "Unknown 0x54",
  "Zenkakuhankaku",
  "102nd",
  "F11",
  "F12",
  "Ro",
  "Katakana",
  "Hiragana",
  "Henkan",
  "Katakanahiragana",
  "Muhenkan",
  "Keypad JP Comma",
  "Keypad Enter",
  "Right Control",
  "Keypad Slash",
  "Sys rq",
  "Right Alt",
  "Line Feed",
  "Home",
  "Up",
  "Page Up",
  "Left",
  "Right",
  "End",
  "Down",
  "Page Down",
  "Insert",
  "Delete",
  "Macro",
  "Mute",
  "Volume Down",
  "Volume Up",
  "Power",
  "Keypad Equal",
  "Keypad Plus Minus",
  "Pause",
  "Unknown 0x78",
  "Keypad Comma",
  "Hanguel",
  "Hanja",
  "Yen",
  "Left Meta",
  "Right Meta",
  "Compose",
  "Stop",
  "Again",
  "Props",
  "Undo",
  "Front",
  "Copy",
  "Open",
  "Paste",
  "Find",
  "Cut",
  "Help",
  "Menu",
  "Calc",
  "Setup",
  "Sleep",
  "Wakeup",
  "File",
  "Send File",
  "Delete File",
  "XFER",
  "Program 1",
  "Program 2",
  "WWW",
  "MS-DOS",
  "Coffee",
  "Direction",
  "Cyclewindows",
  "Mail",
  "Bookmarks",
  "Computer",
  "Back",
  "Forward",
  "Close CD",
  "Eject CD",
  "Eject Close CD",
  "Next Song",
  "Play/Pause",
  "Previous Song",
  "Stop CD",
  "Record",
  "Rewind",
  "Phone",
  "ISO",
  "Config",
  "Homepage",
  "Refresh",
  "Exit",
  "Move",
  "Edit",
  "Scroll UP",
  "Scroll DOWN",
  "Keypad Left Parenthesis",
  "keyapd Right Parenthesis",
  "Unknown 0xb5",
  "Unknown 0xb6",
  "F13",
  "F14",
  "F15",
  "F16",
  "F17",
  "F18",
  "F19",
  "F20",
  "F21",
  "F22",
  "F23",
  "F24",
  "Unknown 0xc3",
  "Unknown 0xc4",
  "Unknown 0xc5",
  "Unknown 0xc6",
  "Unknown 0xc7",
  "Play CD",
  "Pause CD",
  "Program 3",
  "Program 4",
  "Suspend",
  "Close",
  "Play",
  "Fast Forward",
  "Bass Boost",
  "Print",
  "HP",
  "Camera",
  "Sound",
  "Question",
  "E-mail",
  "Chat",
  "Search",
  "Connect",
  "Finance",
  "Sport",
  "Shop",
  "Alterase",
  "Cancel",
  "Brightness Down",
  "Brightness Up",
  "Media",
  "Unknown 0xe3",
  "Unknown 0xe4",
  "Unknown 0xe5",
  "Unknown 0xe6",
  "Unknown 0xe7",
  "Unknown 0xe8",
  "Unknown 0xe9",
  "Unknown 0xea",
  "Unknown 0xeb",
  "Unknown 0xec",
  "Unknown 0xed",
  "Unknown 0xee",
  "Unknown 0xef",
  "Unknown Key",
  "Unknown 0xf1",
  "Unknown 0xf2",
  "Unknown 0xf3",
  "Unknown 0xf4",
  "Unknown 0xf5",
  "Unknown 0xf6",
  "Unknown 0xf7",
  "Unknown 0xf8",
  "Unknown 0xf9",
  "Unknown 0xfa",
  "Unknown 0xfb",
  "Unknown 0xfc",
  "Unknown 0xfd",
  "Unknown 0xfe",
  "Unknown 0xff",
  "Button 0",
  "Button 1",
  "Button 2",
  "Button 3",
  "Button 4",
  "Button 5",
  "Button 6",
  "Button 7",
  "Button 8",
  "Button 9",
  "Unknown 0x10a",
  "Unknown 0x10b",
  "Unknown 0x10c",
  "Unknown 0x10d",
  "Unknown 0x10e",
  "Unknown 0x10f",
  "Mouse Button Left",
  "Mouse Button Right",
  "Mouse Button Middle",
  "Mouse Button Side",
  "Mouse Button Extra",
  "Mouse Button Forward",
  "Mouse Button Back",
  "Mouse Button Task",
  "Unknown 0x118",
  "Unknown 0x119",
  "Unknown 0x11a",
  "Unknown 0x11b",
  "Unknown 0x11c",
  "Unknown 0x11d",
  "Unknown 0x11e",
  "Unknown 0x11f",
  "Joystick Trigger",
  "Joystick Thumb",
  "Joystick Thumb 2",
  "Joystick Top",
  "Joystick Top 2",
  "Joystick Pinkie",
  "Joystick Base",
  "Joystick Base 2",
  "Joystick Base 3",
  "Joystick Base 4",
  "Joystick Base 5",
  "Joystick Base 6",
  "Unknown 0x12c",
  "Unknown 0x12d",
  "Unknown 0x12e",
  "Joystick Dead",
  "Gamepad A",
  "Gamepad B",
  "Gamepad C",
  "Gamepad X",
  "Gamepad Y",
  "Gamepad Z",
  "Gamepad T L",
  "Gamepad T R",
  "Gamepad T L 2",
  "Gamepad T R 2",
  "Gamepad Select",
  "Gamepad Start",
  "Gamepad Mode",
  "Gamepad Thumb L",
  "Gamepad Thumb R",
  "Unknown 0x13f",
  "Tool Pen",
  "Tool Rubber",
  "Tool Brush",
  "Tool Pencil",
  "Tool Airbrush",
  "Tool Finger",
  "Tool Mouse",
  "Tool Lens",
  "Unknown 0x148",
  "Unknown 0x149",
  "Touch",
  "Stylus",
  "Stylus 2",
  "Tool Double Tap",
  "Tool Triple Tap",
  "Unknown 0x14f",
  "Gear Down",
  "Gear Up",
  "Unknown 0x152",
  "Unknown 0x153",
  "Unknown 0x154",
  "Unknown 0x155",
  "Unknown 0x156",
  "Unknown 0x157",
  "Unknown 0x158",
  "Unknown 0x159",
  "Unknown 0x15a",
  "Unknown 0x15b",
  "Unknown 0x15c",
  "Unknown 0x15d",
  "Unknown 0x15e",
  "Unknown 0x15f",
  "Ok",
  "Select ",
  "Goto",
  "Clear",
  "Power 2",
  "Option",
  "Info",
  "Time",
  "Vendor",
  "Archive",
  "Program",
  "Channel",
  "Favorites",
  "EPG",
  "PVR",
  "MHP",
  "Language",
  "Title",
  "Subtitle",
  "Angle",
  "Zoom",
  "Mode",
  "Keyboard",
  "Screen",
  "PC",
  "TV",
  "TV 2",
  "VCR",
  "VCR 2",
  "SAT",
  "SAT 2",
  "CD",
  "Tape",
  "Radio",
  "Tuner",
  "Player",
  "Text",
  "DVD",
  "AUX",
  "MP3",
  "Audio",
  "Video",
  "Directory",
  "List",
  "Memo",
  "Calendar",
  "Red",
  "Green",
  "Yellow",
  "Blue",
  "Channel Up",
  "Channel Down",
  "First",
  "Last",
  "AB",
  "Next",
  "Restart",
  "Slow",
  "Shuffle",
  "Break",
  "Previous",
  "Digits",
  "Teen",
  "Twen",
  "Unknown 0x1a0",
  "Unknown 0x1a1",
  "Unknown 0x1a2",
  "Unknown 0x1a3",
  "Unknown 0x1a4",
  "Unknown 0x1a5",
  "Unknown 0x1a6",
  "Unknown 0x1a7",
  "Unknown 0x1a8",
  "Unknown 0x1a9",
  "Unknown 0x1aa",
  "Unknown 0x1ab",
  "Unknown 0x1ac",
  "Unknown 0x1ad",
  "Unknown 0x1ae",
  "Unknown 0x1af",
  "Unknown 0x1b0",
  "Unknown 0x1b1",
  "Unknown 0x1b2",
  "Unknown 0x1b3",
  "Unknown 0x1b4",
  "Unknown 0x1b5",
  "Unknown 0x1b6",
  "Unknown 0x1b7",
  "Unknown 0x1b8",
  "Unknown 0x1b9",
  "Unknown 0x1ba",
  "Unknown 0x1bb",
  "Unknown 0x1bc",
  "Unknown 0x1bd",
  "Unknown 0x1be",
  "Unknown 0x1bf",
  "Delete EOL",
  "Delete EOS",
  "Insert Line",
  "Delete Line",
  "Unknown 0x1c4",
  "Unknown 0x1c5",
  "Unknown 0x1c6",
  "Unknown 0x1c7",
  "Unknown 0x1c8",
  "Unknown 0x1c9",
  "Unknown 0x1ca",
  "Unknown 0x1cb",
  "Unknown 0x1cc",
  "Unknown 0x1cd",
  "Unknown 0x1ce",
  "Unknown 0x1cf",
  "Fn",
  "Fn Esc",
  "Fn F1",
  "Fn F2",
  "Fn F3",
  "Fn F4",
  "Fn F5",
  "Fn F6",
  "Fn F7",
  "Fn F8",
  "Fn F9",
  "Fn F10",
  "Fn F11",
  "Fn F12",
  "Fn 1",
  "Fn 2",
  "Fn D",
  "Fn E",
  "Fn F",
  "Fn S",
  "Fn B",
  "Unknown 0x1e5",
  "Unknown 0x1e6",
  "Unknown 0x1e7",
  "Unknown 0x1e8",
  "Unknown 0x1e9",
  "Unknown 0x1ea",
  "Unknown 0x1eb",
  "Unknown 0x1ec",
  "Unknown 0x1ed",
  "Unknown 0x1ee",
  "Unknown 0x1ef",
  "Unknown 0x1f0",
  "Unknown 0x1f1",
  "Unknown 0x1f2",
  "Unknown 0x1f3",
  "Unknown 0x1f4",
  "Unknown 0x1f5",
  "Unknown 0x1f6",
  "Unknown 0x1f7",
  "Unknown 0x1f8",
  "Unknown 0x1f9",
  "Unknown 0x1fa",
  "Unknown 0x1fb",
  "Unknown 0x1fc",
  "Unknown 0x1fd",
  "Unknown 0x1fe",
};

#endif
